#!/bin/sh

if [ `id -u` -ne 0 ];then
        echo Please run as root.
        exit 0
fi

if [ -f /etc/hosts.org ];then
        echo found backup of /etc/hosts
else
        echo backup /etc/hosts
        cp /etc/hosts /etc/hosts.org
fi

HOSTADDR="https://raw.githubusercontent.com/googlehosts/hosts/master/hosts-files/hosts"
CMD=""
P_WGET=" -qO /tmp/hosts"
P_CURL=" -so /tmp/hosts"

if [ -f "/usr/local/bin/wget" ]; then
  echo "found wget in local bin"
  CMD="/usr/local/bin/wget "$HOSTADDR$P_WGET
else
    if [ -f "/usr/bin/wget" ]; then
      echo "found wget in bin"
      CMD="/usr/bin/wget "$HOSTADDR$P_WGET
    else
        if [ -f "/usr/bin/curl" ]; then
          echo "found curl in bin"
          CMD="/usr/bin/curl "$HOSTADDR$P_CURL
        fi
    fi
fi

echo "get file from github. process file and going to overwrite the hosts"

$CMD

OSENV=`uname`

case $OSENV in
  Linux)
    sed -i '/::1/d' /tmp/hosts
    sed -i '/127.0.0.1/d' /tmp/hosts
    ;;
  Darwin)  
    sed -i '' '/::1/d' /tmp/hosts
    sed -i '' '/127.0.0.1/d' /tmp/hosts
    ;;
  *)
    exit 1
    ;;
esac

sh -c 'cat /tmp/hosts /etc/hosts.org > /etc/hosts'

# rm -f /tmp/hosts
echo "Done."

echo "head 25 lines:"
head -n 25 /etc/hosts
echo "tail 15 lines:"
tail -n 15 /etc/hosts

